global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  # 1. Signos vitales del ThinkCentre (CPU, RAM, Disco)
  - job_name: 'thinkcentre-hardware'
    static_configs:
      - targets: ['node-exporter:9100']

  # 2. Rendimiento de tus contenedores Docker (FastAPI, Dash, Webhook, etc)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # 3. Rendimiento de la base de datos en Hostinger
  - job_name: 'hostinger-mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']
  # 4. Métricas de Zephyrus
  - job_name: 'zephyrus_windows'
    static_configs:
      - targets: ['192.168.3.202:9182']
      - targets: ['g14server:9182']
  # 5. Métricas de TimescaleDB 
  - job_name: 'timescaledb_telemetry'
    static_configs:
      - targets: ['192.168.3.155:9187'] 
  # 6. Métricas de GPU NVIDIA RTX 3060 en Zephyrus
  - job_name: 'zephyrus_rtx3060'
    static_configs:
      - targets: ['192.168.3.202:20000']
  - job_name: 'jetson_nano_hw'
    static_configs:
      - targets: ['192.168.3.99:9102'] # Métricas de jtop (GPU, Temp, Power)

  - job_name: 'jetson_nano_os'
    static_configs:
      - targets: ['192.168.3.99:9100'] # Métricas estándar de Linux    
      