global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  # 1. Signos vitales del ThinkCentre (CPU, RAM, Disco)
  - job_name: 'thinkcentre-hardware'
    static_configs:
      - targets: ['node-exporter:9100']

  # 2. Rendimiento de tus contenedores Docker (FastAPI, Dash, Webhook, etc)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # 3. Rendimiento de la base de datos en Hostinger
  - job_name: 'hostinger-mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']
  # 4. Métricas de Zephyrus
  - job_name: 'zephyrus_windows'
    static_configs:
      - targets: ['192.168.3.202:9182']
  # 5. Métricas de TimescaleDB 
  - job_name: 'timescaledb_telemetry'
    static_configs:
      - targets: ['192.168.3.155:9187'] 
      #- targets: ['postgres_exporter:9187'] 
      # Usamos el nombre del contenedor y su puerto porque ambos viven en la misma red de Docker